// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuzzleTimer.Models;

#nullable disable

namespace PuzzleTimer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220404224624_Images")]
    partial class Images
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.2.22153.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PuzzleTimer.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PuzzleId")
                        .HasColumnType("int");

                    b.Property<int?>("SolvingSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PuzzleId");

                    b.HasIndex("SolvingSessionId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("PuzzleTimer.Models.Puzzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PieceCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Puzzles");
                });

            modelBuilder.Entity("PuzzleTimer.Models.SolvingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PuzzleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PuzzleId");

                    b.ToTable("SolvingSessions");
                });

            modelBuilder.Entity("PuzzleTimer.Models.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SolvingSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SolvingSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("PuzzleTimer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SolvingSessionUser", b =>
                {
                    b.Property<int>("SolvingSessionsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("SolvingSessionsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("SolvingSessionUser");
                });

            modelBuilder.Entity("PuzzleTimer.Models.Image", b =>
                {
                    b.HasOne("PuzzleTimer.Models.Puzzle", "Puzzle")
                        .WithMany()
                        .HasForeignKey("PuzzleId");

                    b.HasOne("PuzzleTimer.Models.SolvingSession", "SolvingSession")
                        .WithMany()
                        .HasForeignKey("SolvingSessionId");

                    b.Navigation("Puzzle");

                    b.Navigation("SolvingSession");
                });

            modelBuilder.Entity("PuzzleTimer.Models.SolvingSession", b =>
                {
                    b.HasOne("PuzzleTimer.Models.Puzzle", "Puzzle")
                        .WithMany()
                        .HasForeignKey("PuzzleId");

                    b.Navigation("Puzzle");
                });

            modelBuilder.Entity("PuzzleTimer.Models.TimeEntry", b =>
                {
                    b.HasOne("PuzzleTimer.Models.SolvingSession", "SolvingSession")
                        .WithMany("TimeEntries")
                        .HasForeignKey("SolvingSessionId");

                    b.HasOne("PuzzleTimer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("SolvingSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SolvingSessionUser", b =>
                {
                    b.HasOne("PuzzleTimer.Models.SolvingSession", null)
                        .WithMany()
                        .HasForeignKey("SolvingSessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PuzzleTimer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PuzzleTimer.Models.SolvingSession", b =>
                {
                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
